//! Help system — comprehensive CLI documentation.
//! Extracted from main.rs to keep the main file focused on logic.

pub fn print_help() {
    println!("wave-engine v0.1.0 — training engine for wave-coherent neural architectures");
    println!();
    println!("USAGE:");
    println!("    wave-engine <DATA> [OPTIONS]");
    println!();
    println!("ARGUMENTS:");
    println!("    DATA              Path to training data (auto-detects format)");
    println!("                      Supported formats:");
    println!("                        data/input.txt          Plain text");
    println!("                        data/corpus.jsonl       HuggingFace JSONL (extracts 'text' field)");
    println!("                        data/wikitext/          Directory (concatenates .txt + .jsonl)");
    println!("                      Files > 500MB: auto-tokenized to .wtok binary, memory-mapped");
    println!();
    println!("TRAINING:");
    println!("    --iters N         Training iterations                    [default: 500]");
    println!("    --batch N         Batch size                             [default: 4]");
    println!("    --seq N           Sequence length (context window)       [default: 256]");
    println!("    --lr F            Learning rate                          [default: 1e-4]");
    println!("    --layers N        Number of transformer blocks           [default: 24]");
    println!();
    println!("ARCHITECTURE (all tiers — CPU, wgpu, Candle):");
    println!("    --n-bands N       Harmonic frequency bands (n_embd = N×2) [default: 384]");
    println!("    --n-head N        Number of attention heads               [default: 12]");
    println!("    --maestro-dim N   Maestro bottleneck width                [default: 16]");
    println!("    --rk4-steps N     ODE integration steps (CPU/wgpu only)   [default: 16]");
    println!("    --out-proj-groups N  Block-diagonal groups (1=dense)      [default: 6]");
    println!("    --m1 N              Multi-grid modulus 1 (must pair with --m2, coprime)");
    println!("    --m2 N              Multi-grid modulus 2 (must pair with --m1, coprime)");
    println!("    --tied-embeddings   Use harmonic wte as output decoder (zero lm_head params)");
    println!("    --lm-rank N         Low-rank lm_head factoring (0=full rank)  [default: 0]");
    println!("                        Rank 32 at 168-dim: 172K→38K params (78% saving)");
    println!("    --wave-decode       Phase coherence output decoder (85 params vs 172K)");
    println!("    --unfreeze-phases   Learn reference phases (86K params, use with --wave-decode)");
    println!();
    println!("    Common presets:");
    println!("      168-dim:   --n-bands 84   --n-head 4   (fast diagnostic model)");
    println!("      768-dim:   --n-bands 384  --n-head 12  (default)");
    println!("      4096-dim:  --n-bands 2048 --n-head 32  --out-proj-groups 32");
    println!();
    println!("    ODE coupling (linked to AGC ceiling — stronger coupling = tighter ceiling):");
    println!("    --alpha F         ODE self-phase coupling                [default: 0.1]");
    println!("    --beta F          ODE cross-phase coupling               [default: same as alpha]");
    println!("    --agc-ceiling F   AGC max threshold (auto-derived if omitted)");
    println!("      α=0.1:  ceiling = 1.77 (strong coupling, tight AGC — char-level)");
    println!("      α=0.05: ceiling = 2.51 (medium coupling — BPE)");
    println!("      α=0.01: ceiling = 5.60 (weak coupling — large models)");
    println!();
    println!("    Recommended BPE vocab per dimension:");
    println!("      168-dim:  512 vocab  (data/tokenizer_512.json)");
    println!("      384-dim:  2K-4K vocab");
    println!("      768-dim:  50K vocab  (data/tokenizer.json)");
    println!();
    println!("RESUME:");
    println!("    --resume FILE     Resume training from checkpoint.");
    println!("                      CPU/wgpu: WCHK .bin file (restores weights + Adam + RNG)");
    println!("                      Candle:   .safetensors file (restores weights only)");
    println!("    --no-curriculum   Disable progressive band curriculum (all bands from start)");
    println!("    --checkpoint-name Save checkpoint to this filename          [default: checkpoint.bin]");
    println!("    --log-name FILE   Custom training log filename (auto-derived from checkpoint name)");
    println!();
    println!("TOKENIZER:");
    println!("    --bpe             Use BPE tokenizer (GPT-2 style)");
    println!("    --tokenizer FILE  Path to tokenizer.json                 [default: data/tokenizer.json]");
    println!("    (default)         Character-level tokenization");
    println!();
    println!("ACCELERATION:");
    println!("    --gpu             Enable wgpu GPU (Vulkan/Metal/DX12)");
    println!("    --candle          Use Candle CUDA backend (requires --features candle-backend)");
    println!("    --custom-op       Use CustomOp ODE (no autograd graph, faster at 384-dim+)");
    println!("    --cuda-kernel     Use native CUDA kernel (fused AGC+RK4 on GPU, CPU backward)");
    println!("    --gpu-duty N      GPU duty cycle 1-100% (Candle only)          [default: 100]");
    println!("                      50 = work one batch, sleep same duration (~50% GPU usage)");
    println!("                      For hot climates, laptops, shared machines");
    println!();
    println!("PERFORMANCE:");
    println!("    --threads N       Rayon thread pool size (default: half available cores)");
    println!("                      Higher = faster CPU, but leaves less for OS/GPU/Desktop");
    println!();
    println!("MONITORS:");
    println!("    --monitor         Enable per-section pipeline timing (forward profiling)");
    println!("    --debug-nan       Enable per-layer NaN detection (Candle only, ~6x slower)");
    println!("    --health-interval N  Full diagnostic suite every N iters (0=off)    [default: 0]");
    println!("                        13 monitors: attention heads, layer flow, gradient breakdown,");
    println!("                        embedding space (iter 0 only), output distribution, ODE dynamics,");
    println!("                        ODE forward decomposition (damping/phase/FWM per layer),");
    println!("                        ODE backward decomposition (gradient flow per physics term),");
    println!("                        dynamic param trajectories, curriculum transitions,");
    println!("                        checkpoint drift, throughput. All in JSONL.");
    println!("    --freeze-ode        Freeze ODE params (identity backward — legacy behaviour)");
    println!("                        Default: ODE α/β/γ are learnable per layer");
    println!("    --corrector dyn      Per-band phase correction after ODE (default, spring k=0.01)");
    println!("    --corrector off      Disable corrector plate (A/B testing)");
    println!("    --no-corrector       Legacy alias for --corrector off");
    println!("    --phase-native      Train ODE to output in embedding space (no lm_head)");
    println!("                        Dot product loss against frozen embeddings. 55/55 arithmetic.");
    println!("    --phase-temp F      Temperature for phase-native softmax              [default: 1.0]");
    println!("    --fwm-strength F    Four-wave mixing chi coefficient                  [default: 0.0]");
    println!("                        Hamiltonian energy-conserving cubic coupling.");
    println!("                        Recommended: 0.03 (8-12% of ODE derivative).");
    println!("                        Monitor with --health-interval to verify fwm_ratio.");
    println!("    --residual-weight F Scale input in residual connection                [default: 1.0]");
    println!("    --pythagorean       Pythagorean sphere encoding (experimental — 0/10, for research)");
    println!();
    println!("DYNAMIC PARAMETERS (--flag dyn = model decides, --flag V,V = human prescribes):");
    println!("    --layer-scale dyn   Per-layer residual scaling. Spring eq=1.0, k=1.0.");
    println!("    --layer-scale V,V   Fixed per-layer values (comma-separated).");
    println!("    --rk4-weights dyn   Per-layer RK4 integration weights [w0,w1,w2,w3].");
    println!("                        Spring eq=[1/6,1/3,1/3,1/6], k=2.0 (very stiff).");
    println!("                        4 params per layer. Model learns depth-dependent integration.");
    println!("    --wd dyn            Per-group weight decay scaling. Spring eq=1.0, k=1.0.");
    println!("    --wd V,V,V          Fixed per-group WD (per layer + lm_head, comma-separated).");
    println!("                        effective_wd = 0.01 * wd_scale[group].");
    println!("    --harmonics dyn     Per-head learnable harmonic numbers. Spring eq=initial, k=2.0.");
    println!("                        n_head params per layer. Model tunes attention frequency.");
    println!("    --harmonics V,V     Fixed harmonic values (comma-separated per head).");
    println!("    --agc-headroom dyn  Per-layer AGC headroom (sigma). Spring eq=3.0, k=1.0.");
    println!("                        Low headroom = tight compression (L0). High = loose (L3).");
    println!("    --agc-headroom V,V  Fixed per-layer headroom (e.g. 2.0,3.0,3.0,4.0).");
    println!("    --corrector dyn     Per-band phase correction after ODE. Spring eq=0.0, k=0.01.");
    println!("                        Very loose spring — corrections earned easily.");
    println!("    --corrector off     Disable corrector plate entirely.");
    println!("    --lr-scale dyn      Per-group LR scaling. Spring eq=1.0, k=0.5.");
    println!("    --lr-scale V,V,V    Fixed per-group LR (per layer + head, comma-separated).");
    println!("    --spring F          Global spring constant for all dynamic params [default: 0.1]");
    println!("                        Restoring force toward equilibrium, not a hard clamp.");
    println!("    --active-layers N   First N layers start at scale=1.0, rest at scale=0.0.");
    println!("");
    println!("  Diagnostics:");
    println!("    --ode-monitor       Show raw per-band ODE data for a prompt");
    println!("    --phase-decode      Compare lm_head vs phase coherence decoding");
    println!("    --head-lr-floor F   Minimum effective LR for lm_head (prevents starvation)");
    println!();
    println!("    Always-on telemetry (no flag needed):");
    println!("      training_log_cpu.jsonl    CPU tier telemetry (per-iteration)");
    println!("      training_log_wgpu.jsonl   wgpu tier telemetry");
    println!("      training_log_candle.jsonl Candle tier telemetry");
    println!("      Cosine LR schedule   Warmup 100 iters, cosine decay to 10% (all tiers)");
    println!("      Pre-flight checks    Embedding separation, param balance, ODE stability");
    println!("      First-10 health      Gradient norms, component balance (first 10 iters)");
    println!("      NaN post-mortem      Which batch elements caused NaN, grad state");
    println!("      NaN recovery         Skips corrupted steps, logs count, continues");
    println!("      Grad norm            Displayed every 10 iters");
    println!("      VRAM monitoring      CUDA memory usage (Candle tier)");
    println!();
    println!("    Built-in architecture features:");
    println!("      Multi-grid embedding Two coprime circles for token separation (automatic)");
    println!("      Per-band ODE clamp   Prevents phase wrapping at small dims (automatic)");
    println!("      AdamW weight decay   0.01 default (prevents weight growth)");
    println!();
    println!("    Per-section profiling (--monitor flag):");
    println!("      [FFN fwd]   mae_in, ODE, mae_out, out_proj — per block timing");
    println!("      [FFN bwd]   out_proj backward timing");
    println!("      [VRAM]      GPU memory at each pipeline stage (Candle, first 5 iters)");
    println!();
    println!("GENERATION:");
    println!("    --generate          Autoregressive text generation from checkpoint");
    println!("                        Requires --resume <checkpoint> --data <training_data>");
    println!("    --prompt TEXT       Starting text for generation                [default: varies]");
    println!("    --max-tokens N      Number of tokens to generate               [default: 100]");
    println!("    --temperature F     Sampling temperature (0=greedy)             [default: 0.0]");
    println!("                        Phase-native: dot product against embeddings (unified decode)");
    println!();
    println!("SERVING:");
    println!("    --serve             Start OpenAI-compatible API server (requires --features serve)");
    println!("                        Requires --resume <checkpoint>. Uses KV-cache for fast generation.");
    println!("    --port N            Server port                                [default: 8080]");
    println!("    --host ADDR         Server bind address                        [default: 127.0.0.1]");
    println!("    --model-name NAME   Model name in API responses                [default: wave-engine]");
    println!("    --api-key KEY       Bearer token for API authentication (optional)");
    println!();
    println!("ARCHITECTURE CALCULATOR:");
    println!("    --recommend FILE    Analyze dataset and recommend optimal architecture");
    println!("                        Two-bottleneck model: bands + attention must both pass.");
    println!("                        Prints configuration, warnings, and copy-paste CLI commands.");
    println!("    --task TYPE         Override task detection (arithmetic/words/grammar/language)");
    println!();
    println!("ANALYSIS:");
    println!("    --analyze         Run wave structure diagnostics on a trained model (no training)");
    println!("                      Requires --resume <checkpoint>. Uses cos(n*dtheta) harmonic coherence.");
    println!("                      Reports: semantic discrimination, depth curve, band census,");
    println!("                      phase clustering, harmonic spectra. Output: console + analysis/wave_report.json");
    println!();
    println!("    --check-gradients   Finite-difference gradient checker for ODE backward pass.");
    println!("                        Runs at given config, reports PASS/FAIL per parameter.");
    println!("                        Includes FWM Jacobian: tests d_input, d_alpha, d_beta,");
    println!("                        d_gamma, d_chi. 172/172 at 84 bands with chi=0.03.");
    println!("    --galaxy-scan       Generate a galaxy map of the learned harmonic structure.");
    println!("                        Requires --resume <checkpoint>. Pure-band geometric scan:");
    println!("                        per-band 3D positions, pairwise angular geometry with catalog");
    println!("                        matching (11 relationship types), triads, FWM quartets,");
    println!("                        multi-grid decomposition. Auto-runs at end of training.");
    println!("                        Output: <checkpoint>_galaxy/ with galaxy_map.json,");
    println!("                        galaxy_matrix.bin, phases.bin.");
    println!("    --sub-harmonic      Include sub-harmonic diagnostics (with --analyze)");
    println!("    --ode-monitor       Show raw per-band ODE data for a prompt");
    println!("    --compare TEXT      Compare two prompts in ODE monitor mode");
    println!("    --phase-decode      Compare lm_head vs phase coherence decoding");
    println!();
    println!("SCALING:");
    println!("    --scale             Scale checkpoint to different dimensions");
    println!("    --target-bands N    Target band count for scaling");
    println!("    --target-head N     Target head count for scaling");
    println!("    --target-layers N   Target layer count for scaling");
    println!("    --output FILE       Output path for scaled checkpoint   [default: scaled_checkpoint.bin]");
    println!();
    println!("CHECKPOINTS (saved every 500 iters, WCHK v4):");
    println!("    checkpoint.bin                              WCHK v4 — includes chi, wave-server compatible");
    println!("    candle_checkpoint_iter500_loss6.82.safetensors  Candle resume (loss in name)");
    println!("    checkpoint_iter500.bin                      CPU/wgpu resume");
    println!("    WCHK v4: persists chi (FWM strength) — resume preserves wave mixing config.");
    println!("    NaN guard: corrupted checkpoints are NOT saved (loss=NaN/0.0 skipped)");
    println!();
    println!("EXAMPLES:");
    println!("    # 168-dim diagnostic model with 512 BPE");
    println!("    wave-engine data/input.txt --layers 4 --n-bands 84 --n-head 4 \\");
    println!("        --bpe --tokenizer data/tokenizer_512.json --iters 20000");
    println!();
    println!("    # Quick char-level test");
    println!("    wave-engine data/input.txt --layers 4 --iters 100 --seq 64");
    println!();
    println!("    # Full BPE training with Candle CUDA");
    println!("    wave-engine data/input.txt --candle --bpe --iters 3000 --batch 8");
    println!();
    println!("    # Resume from checkpoint");
    println!("    wave-engine data/input.txt --resume checkpoint.bin --iters 20000");
    println!();
    println!("    # Analyse trained model");
    println!("    wave-engine --analyze --resume checkpoint.bin --layers 4 --n-bands 84 --n-head 4");
    println!();
    println!("WAVE-PROBE (separate binary — ODE scattering analysis):");
    println!("    wave-probe --mode MODE [OPTIONS]");
    println!("    Modes: single-band, two-band-constructive, two-band-destructive,");
    println!("           linearity-check, magnitude-sweep, spectral, determinism,");
    println!("           energy-conservation, four-wave-mixing, sweep, all");
    println!("    --input-magnitude F   Scale input amplitude (1.3 = training regime)  [default: 1.0]");
    println!("    --load-checkpoint F   Probe a trained model with per-layer learned weights");
    println!("                          Requires --n-bands, --n-head, --layers matching checkpoint.");
    println!("    --sweep-param NAME    Parameter to sweep (chi, alpha, beta, gamma, input_magnitude)");
    println!("    --sweep-range S,E,D   Sweep start,end,step (e.g. 0.0,0.5,0.05)");
    println!("    Physics decomposition (damping/phase/FWM) reported for every mode.");
    println!("    Energy conservation test validates Hamiltonian correctness.");
    println!("    FWM phase-matching test confirms quartet selectivity.");
    println!();
    println!("THREE TIERS:");
    println!("    CPU       Any hardware, RK4-16 ODE, gold standard precision");
    println!("    wgpu GPU  Any GPU via Vulkan/Metal/DX12 (--gpu), fused GPU ODE");
    println!("    Candle    NVIDIA CUDA (--candle), perturbative ODE, block-diagonal out_proj");
    println!();
    println!("SOURCE: https://github.com/atech-hub/wave-engine");
    println!("SERVER: https://github.com/atech-hub/wave-server");
}
