//! Help system — comprehensive CLI documentation.
//! Extracted from main.rs to keep the main file focused on logic.

pub fn print_help() {
    println!("wave-engine v0.1.0 — training engine for wave-coherent neural architectures");
    println!();
    println!("USAGE:");
    println!("    wave-engine <DATA> [OPTIONS]");
    println!();
    println!("ARGUMENTS:");
    println!("    DATA              Path to training data file (e.g. data/input.txt)");
    println!();
    println!("TRAINING:");
    println!("    --iters N         Training iterations                    [default: 500]");
    println!("    --batch N         Batch size                             [default: 4]");
    println!("    --seq N           Sequence length (context window)       [default: 256]");
    println!("    --lr F            Learning rate                          [default: 1e-4]");
    println!("    --layers N        Number of transformer blocks           [default: 24]");
    println!();
    println!("ARCHITECTURE (all tiers — CPU, wgpu, Candle):");
    println!("    --n-bands N       Harmonic frequency bands (n_embd = N×2) [default: 384]");
    println!("    --n-head N        Number of attention heads               [default: 12]");
    println!("    --maestro-dim N   Maestro bottleneck width                [default: 16]");
    println!("    --rk4-steps N     ODE integration steps (CPU/wgpu only)   [default: 16]");
    println!("    --out-proj-groups N  Block-diagonal groups (1=dense)      [default: 6]");
    println!("    --m1 N              Multi-grid modulus 1 (must pair with --m2, coprime)");
    println!("    --m2 N              Multi-grid modulus 2 (must pair with --m1, coprime)");
    println!("    --tied-embeddings   Use harmonic wte as output decoder (zero lm_head params)");
    println!("    --lm-rank N         Low-rank lm_head factoring (0=full rank)  [default: 0]");
    println!("                        Rank 32 at 168-dim: 172K→38K params (78% saving)");
    println!("    --wave-decode       Phase coherence output decoder (85 params vs 172K)");
    println!("    --unfreeze-phases   Learn reference phases (86K params, use with --wave-decode)");
    println!();
    println!("    Common presets:");
    println!("      168-dim:   --n-bands 84   --n-head 4   (fast diagnostic model)");
    println!("      768-dim:   --n-bands 384  --n-head 12  (default)");
    println!("      4096-dim:  --n-bands 2048 --n-head 32  --out-proj-groups 32");
    println!();
    println!("    ODE coupling (linked to AGC ceiling — stronger coupling = tighter ceiling):");
    println!("    --alpha F         ODE self-phase coupling                [default: 0.1]");
    println!("    --beta F          ODE cross-phase coupling               [default: same as alpha]");
    println!("    --agc-ceiling F   AGC max threshold (auto-derived if omitted)");
    println!("      α=0.1:  ceiling = 1.77 (strong coupling, tight AGC — char-level)");
    println!("      α=0.05: ceiling = 2.51 (medium coupling — BPE)");
    println!("      α=0.01: ceiling = 5.60 (weak coupling — large models)");
    println!();
    println!("    Recommended BPE vocab per dimension:");
    println!("      168-dim:  512 vocab  (data/tokenizer_512.json)");
    println!("      384-dim:  2K-4K vocab");
    println!("      768-dim:  50K vocab  (data/tokenizer.json)");
    println!();
    println!("RESUME:");
    println!("    --resume FILE     Resume training from checkpoint.");
    println!("                      CPU/wgpu: WCHK .bin file (restores weights + Adam + RNG)");
    println!("                      Candle:   .safetensors file (restores weights only)");
    println!("    --no-curriculum   Disable progressive band curriculum (all bands from start)");
    println!("    --checkpoint-name Save checkpoint to this filename          [default: checkpoint.bin]");
    println!("    --log-name FILE   Custom training log filename (auto-derived from checkpoint name)");
    println!();
    println!("TOKENIZER:");
    println!("    --bpe             Use BPE tokenizer (GPT-2 style)");
    println!("    --tokenizer FILE  Path to tokenizer.json                 [default: data/tokenizer.json]");
    println!("    (default)         Character-level tokenization");
    println!();
    println!("ACCELERATION:");
    println!("    --gpu             Enable wgpu GPU (Vulkan/Metal/DX12)");
    println!("    --candle          Use Candle CUDA backend (requires --features candle-backend)");
    println!();
    println!("PERFORMANCE:");
    println!("    --threads N       Rayon thread pool size (default: half available cores)");
    println!("                      Higher = faster CPU, but leaves less for OS/GPU/Desktop");
    println!();
    println!("MONITORS:");
    println!("    --monitor         Enable per-section pipeline timing (forward profiling)");
    println!("    --debug-nan       Enable per-layer NaN detection (Candle only, ~6x slower)");
    println!("    --health-interval N  Encoding health sample every N iters (0=off)  [default: 0]");
    println!("                        Logs θ/Δθ balance, entropy, coupling to JSONL");
    println!("    --freeze-ode        Freeze ODE params (identity backward — legacy behaviour)");
    println!();
    println!("    Always-on telemetry (no flag needed):");
    println!("      training_log_cpu.jsonl    CPU tier telemetry (per-iteration)");
    println!("      training_log_wgpu.jsonl   wgpu tier telemetry");
    println!("      training_log_candle.jsonl Candle tier telemetry");
    println!("      Cosine LR schedule   Warmup 100 iters, cosine decay to 10% (all tiers)");
    println!("      Pre-flight checks    Embedding separation, param balance, ODE stability");
    println!("      First-10 health      Gradient norms, component balance (first 10 iters)");
    println!("      NaN post-mortem      Which batch elements caused NaN, grad state");
    println!("      NaN recovery         Skips corrupted steps, logs count, continues");
    println!("      Grad norm            Displayed every 10 iters");
    println!("      VRAM monitoring      CUDA memory usage (Candle tier)");
    println!();
    println!("    Built-in architecture features:");
    println!("      Multi-grid embedding Two coprime circles for token separation (automatic)");
    println!("      Per-band ODE clamp   Prevents phase wrapping at small dims (automatic)");
    println!("      AdamW weight decay   0.01 default (prevents weight growth)");
    println!();
    println!("    Per-section profiling (--monitor flag):");
    println!("      [FFN fwd]   mae_in, ODE, mae_out, out_proj — per block timing");
    println!("      [FFN bwd]   out_proj backward timing");
    println!("      [VRAM]      GPU memory at each pipeline stage (Candle, first 5 iters)");
    println!();
    println!("ANALYSIS:");
    println!("    --analyze         Run wave structure diagnostics on a trained model (no training)");
    println!("                      Requires --resume <checkpoint>. Uses cos(n*dtheta) harmonic coherence.");
    println!("                      Reports: semantic discrimination, depth curve, band census,");
    println!("                      phase clustering, harmonic spectra. Output: console + analysis/wave_report.json");
    println!();
    println!("    Example:");
    println!("    wave-engine --analyze --resume checkpoint.bin --layers 24 --out-proj-groups 6");
    println!("    wave-engine --analyze --resume checkpoint.bin --layers 4 --bpe --tokenizer data/tokenizer.json");
    println!();
    println!("CHECKPOINTS (saved every 500 iters, WCHK v2):");
    println!("    checkpoint.bin                              WCHK — wave-server compatible");
    println!("    candle_checkpoint_iter500_loss6.82.safetensors  Candle resume (loss in name)");
    println!("    checkpoint_iter500.bin                      CPU/wgpu resume");
    println!("    NaN guard: corrupted checkpoints are NOT saved (loss=NaN/0.0 skipped)");
    println!();
    println!("EXAMPLES:");
    println!("    # 168-dim diagnostic model with 512 BPE");
    println!("    wave-engine data/input.txt --layers 4 --n-bands 84 --n-head 4 \\");
    println!("        --bpe --tokenizer data/tokenizer_512.json --iters 20000");
    println!();
    println!("    # Quick char-level test");
    println!("    wave-engine data/input.txt --layers 4 --iters 100 --seq 64");
    println!();
    println!("    # Full BPE training with Candle CUDA");
    println!("    wave-engine data/input.txt --candle --bpe --iters 3000 --batch 8");
    println!();
    println!("    # Resume from checkpoint");
    println!("    wave-engine data/input.txt --resume checkpoint.bin --iters 20000");
    println!();
    println!("    # Analyse trained model");
    println!("    wave-engine --analyze --resume checkpoint.bin --layers 4 --n-bands 84 --n-head 4");
    println!();
    println!("THREE TIERS:");
    println!("    CPU       Any hardware, RK4-16 ODE, gold standard precision");
    println!("    wgpu GPU  Any GPU via Vulkan/Metal/DX12 (--gpu), fused GPU ODE");
    println!("    Candle    NVIDIA CUDA (--candle), perturbative ODE, block-diagonal out_proj");
    println!();
    println!("SOURCE: https://github.com/atech-hub/wave-engine");
    println!("SERVER: https://github.com/atech-hub/wave-server");
}
